#a program to input 8 nummbers from the user and display all thr unique numbers(once)
set = set()# empty set
n=input("Enter number 1: ")
set.add(int(n))
n=input("Enter number 1: ")
set.add(int(n))
n=input("Enter number 1: ")
set.add(int(n))
n=input("Enter number 1: ")
set.add(int(n))
n=input("Enter number 1: ")
set.add(int(n))
n=input("Enter number 1: ")
set.add(int(n))
n=input("Enter number 1: ")
set.add(int(n))
n=input("Enter number 1: ")
set.add(int(n))
print(set)