# create an empty dictionary.allow 4 friends to enter their fav lang as valu and use key as their name.ASSUME  THAT NAME ARE UNIQUE
dict={}
name = input("Enter friends name:")
lang = input("Enter language name : ")
dict.update({name:lang})
name = input("Enter friends name:")
lang = input("Enter language name : ")
dict.update({name:lang})
name = input("Enter friends name:")
lang = input("Enter language name : ")
dict.update({name:lang})
# name = input("Enter friends name:")
# lang = input("Enter language name : ")
# dict.update({name:lang})
# name = input("Enter friends name:")
# lang = input("Enter language name : ")
# dict.update({name:lang})
# name = input("Enter friends name:")
# name = input("Enter friends name:")
# lang = input("Enter language name : ")
# dict.update({name:lang})
# name = input("Enter friends name:")
# lang = input("Enter language name : ")
# dict.update({name:lang})
# lang = input("Enter language name : ")
# dict.update({name:lang})
# name = input("Enter friends name:")
# lang = input("Enter language name : ")
# dict.update({name:lang})
# name = input("Enter friends name:")
# lang = input("Enter language name : ")
# dict.update({name:lang})
# name = input("Enter friends name:")
# lang = input("Enter language name : ")
# dict.update({name:lang})
print(dict)
