#ENTER STUDENTS MARK IN  A TUPPPLE AMD DISPLAY IN A SORTED A MANNERR
marks=[]
m1=int.input(("Enter the mark:"))
marks.append(m1)
m1=int.input(("Enter the mark:"))
marks.append(m1)
m1=int.input(("Enter the mark:"))
marks.append(m1)
m1=int.input(("Enter the mark:"))
marks.append(m1)
m1=int.input(("Enter the mark:"))
marks.append(m1)
m1=int.input(("Enter the mark:"))
marks.append(m1)
m1=int.input(("Enter the mark:"))
marks.append(m1)
m1=int.input(("Enter the mark:"))
marks.append(m1)


marks.sort()
print(marks)